### ISSUE TITLE
Create react app

### ISSUE THREAD

**Issue by JCresent** [JCresent/RONR_Web_App#9]
- Create a react app in this repo   
- Migrate all html pages to jsx

**Comment by Nilesh270** [comment]
I will do this !!

**Comment by JCresent** [comment]
Got it, made some changes already so make sure to review those in this branch before doing any work! 

TODO: 
- Still need to convert the other two pages, password reset and registration, to jsx (or js if we want to go that route) 

- Was also thinking about organizing a better structure for all the files (such as pairing css and jsx files in one file, having a components file, etc.)
